Import patches-unapplied version 1.0.9-2 to ubuntu/breezy
Imported using git-ubuntu import.

Changelog parent: ede111631ef93295dafeb08d8f0d7dc8274ac8b6

New changelog entries:
  * Thomas Hood
    - Conflict with pre-1.0.9 libasound2-plugins
  * New upstream release
    - Fix bug that disabled stack protection (CAN-2005-0087)
      (RedHat bug #144518)  (Closes: #301164)
    - Fixes related to mplayer (Closes: #310189)
  * Jordi Mallach
    - debian/rules: bump shlibs to 1.0.9.
  * New upstream release
    - Closes: #291533 "ttable in .asoundrc do not accept fractions"
    - Closes: #293928 "wrong routings of channels for 5.1 ICH5"
    - Closes: #299423 "Please include asound_fm.h"
    - Closes: #300792 "FTBFS (ppc64/gcc-4.0): static declaration ..."
    - libasound2-plugins is no longer built from this source package
  * Thomas Hood
    - Remove the control entry, commands in rules, build dependencies
      related to libasound2-plugins
    - Add some mutual Suggestions among the ALSA library packages
    - Drop dpatch applied upstream: 10_conf-space-fix
    - debian/NOTES:
      + Add note about what to do if we ever have libasound3
      + Remove note about building libasound2-plugins
    - Tweak descriptions
  * Thomas Hood:
    - debian/control
      + s/alsalib-dev/libasound-dev/ in libasound2-dev's Conflicts: and
        Provides:, to use a more standard naming scheme
  * Thomas Hood:
    - Add 10_conf-space-fix.dpatch so that libasound2 works with sound
      card names containing spaces  (Closes: #294880, #293907)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1033,6 +1033,8 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-resmgr         support resmgr (optional)
+  --disable-aload         disable reading /dev/aload*
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1822,7 +1824,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=alsa-lib
- VERSION=1.0.8
+ VERSION=1.0.9
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3665,7 +3667,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3668 "configure"' > conftest.$ac_ext
+  echo '#line 3670 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5162,7 +5164,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5165:" \
+echo "$as_me:5167:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6167,11 +6169,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6170: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6172: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6174: \$? = $ac_status" >&5
+   echo "$as_me:6176: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6399,11 +6401,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6402: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6404: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6406: \$? = $ac_status" >&5
+   echo "$as_me:6408: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6466,11 +6468,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6469: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6471: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6473: \$? = $ac_status" >&5
+   echo "$as_me:6475: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8485,7 +8487,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8488 "configure"
+#line 8490 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8583,7 +8585,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8586 "configure"
+#line 8588 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10715,11 +10717,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10718: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10720: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10722: \$? = $ac_status" >&5
+   echo "$as_me:10724: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10782,11 +10784,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10785: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10787: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10789: \$? = $ac_status" >&5
+   echo "$as_me:10791: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12032,7 +12034,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12035 "configure"
+#line 12037 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12130,7 +12132,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12133 "configure"
+#line 12135 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12952,11 +12954,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12955: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12957: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12959: \$? = $ac_status" >&5
+   echo "$as_me:12961: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13019,11 +13021,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13022: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13024: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13026: \$? = $ac_status" >&5
+   echo "$as_me:13028: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14966,11 +14968,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14969: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14971: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14973: \$? = $ac_status" >&5
+   echo "$as_me:14975: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15198,11 +15200,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15201: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15203: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15205: \$? = $ac_status" >&5
+   echo "$as_me:15207: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15265,11 +15267,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15268: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15270: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15272: \$? = $ac_status" >&5
+   echo "$as_me:15274: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17284,7 +17286,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17287 "configure"
+#line 17289 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17382,7 +17384,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17385 "configure"
+#line 17387 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19117,13 +19119,119 @@ echo "${ECHO_T}$host_cpu" >&6
   ;;
 esac
 
+echo "$as_me:$LINENO: checking for resmgr support" >&5
+echo $ECHO_N "checking for resmgr support... $ECHO_C" >&6
+# Check whether --enable-resmgr or --disable-resmgr was given.
+if test "${enable_resmgr+set}" = set; then
+  enableval="$enable_resmgr"
+  resmgr="$enableval"
+else
+  resmgr="no"
+fi;
+echo "$as_me:$LINENO: result: $resmgr" >&5
+echo "${ECHO_T}$resmgr" >&6
+if test "$resmgr" = "yes"; then
+
+echo "$as_me:$LINENO: checking for rsm_open_device in -lresmgr" >&5
+echo $ECHO_N "checking for rsm_open_device in -lresmgr... $ECHO_C" >&6
+if test "${ac_cv_lib_resmgr_rsm_open_device+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lresmgr  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char rsm_open_device ();
+int
+main ()
+{
+rsm_open_device ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_resmgr_rsm_open_device=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_resmgr_rsm_open_device=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_resmgr_rsm_open_device" >&5
+echo "${ECHO_T}$ac_cv_lib_resmgr_rsm_open_device" >&6
+if test $ac_cv_lib_resmgr_rsm_open_device = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBRESMGR 1
+_ACEOF
+
+  LIBS="-lresmgr $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Cannot find libresmgr" >&5
+echo "$as_me: error: Cannot find libresmgr" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define SUPPORT_RESMGR "1"
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking for aload* support" >&5
+echo $ECHO_N "checking for aload* support... $ECHO_C" >&6
+# Check whether --enable-aload or --disable-aload was given.
+if test "${enable_aload+set}" = set; then
+  enableval="$enable_aload"
+  aload="$enableval"
+else
+  aload="yes"
+fi;
+echo "$as_me:$LINENO: result: $aload" >&5
+echo "${ECHO_T}$aload" >&6
+if test "$aload" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define SUPPORT_ALOAD "1"
+_ACEOF
+
+fi
+
 if test ! -L include/alsa ; then
   echo "Making a symlink include/alsa"
   rm -f include/alsa
   ln -sf . include/alsa
 fi
 
-                                                                                                                                                                                                                                                                                                  ac_config_files="$ac_config_files Makefile doc/Makefile doc/pictures/Makefile include/Makefile include/sound/Makefile src/Makefile src/control/Makefile src/mixer/Makefile src/ordinary_mixer/Makefile src/pcm/Makefile src/pcm/ext/Makefile src/pcm/scopes/Makefile src/ordinary_pcm/Makefile src/rawmidi/Makefile src/timer/Makefile src/hwdep/Makefile src/seq/Makefile src/instr/Makefile src/compat/Makefile src/alisp/Makefile src/conf/Makefile src/conf/cards/Makefile src/conf/pcm/Makefile alsalisp/Makefile aserver/Makefile test/Makefile utils/Makefile utils/alsa-lib.spec utils/alsa.pc"
+                                                                                                                                                                                                                                                                                        ac_config_files="$ac_config_files Makefile doc/Makefile doc/pictures/Makefile include/Makefile include/sound/Makefile src/Makefile src/control/Makefile src/mixer/Makefile src/ordinary_mixer/Makefile src/pcm/Makefile src/pcm/scopes/Makefile src/ordinary_pcm/Makefile src/rawmidi/Makefile src/timer/Makefile src/hwdep/Makefile src/seq/Makefile src/instr/Makefile src/compat/Makefile src/alisp/Makefile src/conf/Makefile src/conf/cards/Makefile src/conf/pcm/Makefile alsalisp/Makefile aserver/Makefile test/Makefile utils/Makefile utils/alsa-lib.spec utils/alsa.pc"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -19710,7 +19818,6 @@ do
   "src/mixer/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/mixer/Makefile" ;;
   "src/ordinary_mixer/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ordinary_mixer/Makefile" ;;
   "src/pcm/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/pcm/Makefile" ;;
-  "src/pcm/ext/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/pcm/ext/Makefile" ;;
   "src/pcm/scopes/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/pcm/scopes/Makefile" ;;
   "src/ordinary_pcm/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/ordinary_pcm/Makefile" ;;
   "src/rawmidi/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/rawmidi/Makefile" ;;
